# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

includes:
  dev:
    taskfile: .taskfiles/Dev.yml
    flatten: true
    dir: .

tasks:
  default:
    cmds:
      - task -l
    silent: true
